[package]
name = "persichetti"
version = "0.1.0"
authors = ["Kyle Silver"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.13"
itertools = "0.10.0"
lazy_static = "1.4"
regex = "1"